### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by sonegishi**
@ShutoAraki Sorry, I should have checked when I was reviewing.

### CODE REVIEW

**Comment by ShutoAraki** [comment]
Should we capitalize the first character of each method in C++? Is that a standard practice? I know it was on the instruction, but I thought we only capitalize the first character for classes and structs only...

**Comment by ShutoAraki** [comment]
Also I didn't merge the `add_circleci` branch with master yet so that's why circleci is failing rn lol

**Comment by ShutoAraki** [comment]
LGTM but I personally didn't wanna capitalize the first characters haha

**Comment by sonegishi** [comment]
@ShutoAraki 
>Should we capitalize the first character of each method in C++? Is that a standard practice? I know it was on the instruction, but I thought we only capitalize the first character for classes and structs only...

I know...but he said in the instruction that he will deduct a score if not followed.


```
Make sure that you name your classes and methods exactly as I have typed them in the instructions – lowercase/uppercase matters. If a class or method is not named appropriately, it will result in a loss of points for those classes/methods.
```

**Comment by ShutoAraki** [comment]
> @ShutoAraki
> 
> > Should we capitalize the first character of each method in C++? Is that a standard practice? I know it was on the instruction, but I thought we only capitalize the first character for classes and structs only...
> 
> I know...but he said in the instruction that he will deduct a score if not followed.
> 
> ```
> Make sure that you name your classes and methods exactly as I have typed them in the instructions – lowercase/uppercase matters. If a class or method is not named appropriately, it will result in a loss of points for those classes/methods.
> ```

Oh shit okay lol

**Pull request merged**
