### PR TITLE
Checkpoint 3

### PR DESCRIPTION
**Pull request by ShutoAraki**
- [x]  Vector4 struct

- [x]  Matrix4 struct

- [x]  3D Transformation

- [x]  Triangle3D struct

- [x]  Raster drawTriangle method

- [x] Triangle2D struct

- [x]  Complete the drawTringle()

- [x]  Model class

- [x]  drawModel() method

### CODE REVIEW

**Comment by ShutoAraki** [comment]
image
The model somehow looks like this...

**Comment by ShutoAraki** [comment]
@sonegishi I changed my tab space setting to 4 spaces at some point and there are some disgusting tab inconsistencies in different files. Some are 2 spaced and others are 4 spaced. Can you do the minor fix at some point lol

**Comment by ShutoAraki** [comment]
@sonegishi Before that can you test if this is working?

**Comment by sonegishi** [comment]
> @sonegishi Before that can you test if this is working?

Yep

**Pull request merged**
